# Generated by Django 4.1 on 2024-12-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(default='', max_length=20)),
                ('last_name', models.CharField(blank=True, default='', max_length=20)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(default='', max_length=10)),
                ('main_goal', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('inst', models.CharField(blank=True, default='', max_length=100)),
                ('telegram', models.CharField(blank=True, default='', max_length=100)),
                ('x_network', models.CharField(blank=True, default='', max_length=100)),
                ('hobby', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(default='', max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo1', models.ImageField(default=None, upload_to='images/')),
                ('photo2', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('photo3', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('photo4', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('photo5', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('photo6', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('liked_profiles', models.TextField(blank=True, default='')),
                ('reported', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('role', models.IntegerField(choices=[(0, 'visitor'), (1, 'admin')], default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
