# Generated by Django 4.1 on 2024-11-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo1',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo2',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo3',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
