# Generated by Django 4.1 on 2024-12-15 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hobby',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='inst',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='main_goal',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo4',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo5',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo6',
            field=models.ImageField(default=None, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='telegram',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='x_network',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
